services:
  db:
    image: postgres:15.4-alpine
    container_name: tgbot_db
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: db_name
        POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: db_password
      DATABASE_NAME: db_name
      DATABASE_USER: postgres
      SECRET_KEY: your_secret_key
      BOT_API_TOKEN: your_bot_api_token